/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  announcement: () => import("@/views/announcement/index.vue"),
  appeal: () => import("@/views/appeal/index.vue"),
  "billing-rule": () => import("@/views/billing-rule/index.vue"),
  blacklist: () => import("@/views/blacklist/index.vue"),
  coupon: () => import("@/views/coupon/index.vue"),
  home: () => import("@/views/home/index.vue"),
  order: () => import("@/views/order/index.vue"),
  "parking-lot": () => import("@/views/parking-lot/index.vue"),
  "parking-space": () => import("@/views/parking-space/index.vue"),
  payment: () => import("@/views/payment/index.vue"),
  reservation: () => import("@/views/reservation/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
