/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'announcement',
    path: '/announcement',
    component: 'layout.base$view.announcement',
    meta: {
      title: '公告管理',
      icon: 'mdi:bullhorn-outline',
      order: 11,
      i18nKey: 'route.announcement'
    }
  },
  {
    name: 'appeal',
    path: '/appeal',
    component: 'layout.base$view.appeal',
    meta: {
      title: '异常申诉',
      icon: 'mdi:message-alert-outline',
      order: 10,
      i18nKey: 'route.appeal'
    }
  },
  {
    name: 'billing-rule',
    path: '/billing-rule',
    component: 'layout.base$view.billing-rule',
    meta: {
      title: '计费规则',
      icon: 'mdi:calculator-variant',
      order: 7,
      i18nKey: 'route.billing-rule'
    }
  },
  {
    name: 'blacklist',
    path: '/blacklist',
    component: 'layout.base$view.blacklist',
    meta: {
      title: '黑名单管理',
      icon: 'mdi:cancel',
      order: 9,
      i18nKey: 'route.blacklist'
    }
  },
  {
    name: 'coupon',
    path: '/coupon',
    component: 'layout.base$view.coupon',
    meta: {
      title: '优惠券管理',
      icon: 'mdi:ticket-percent',
      order: 8,
      i18nKey: 'route.coupon'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '控制台',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base$view.order',
    meta: {
      title: '订单管理',
      icon: 'mdi:receipt-text-outline',
      order: 5,
      i18nKey: 'route.order'
    }
  },
  {
    name: 'parking-lot',
    path: '/parking-lot',
    component: 'layout.base$view.parking-lot',
    meta: {
      title: '停车场管理',
      icon: 'mdi:parking',
      order: 2,
      i18nKey: 'route.parking-lot'
    }
  },
  {
    name: 'parking-space',
    path: '/parking-space',
    component: 'layout.base$view.parking-space',
    meta: {
      title: '车位管理',
      icon: 'mdi:car-brake-parking',
      order: 3,
      i18nKey: 'route.parking-space'
    }
  },
  {
    name: 'payment',
    path: '/payment',
    component: 'layout.base$view.payment',
    meta: {
      title: '支付流水',
      icon: 'mdi:credit-card-outline',
      order: 6,
      i18nKey: 'route.payment'
    }
  },
  {
    name: 'reservation',
    path: '/reservation',
    component: 'layout.base$view.reservation',
    meta: {
      title: '预约管理',
      icon: 'mdi:calendar-clock',
      order: 4,
      i18nKey: 'route.reservation'
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base$view.user',
    meta: {
      title: '用户管理',
      icon: 'mdi:account-group-outline',
      order: 12,
      i18nKey: 'route.user'
    }
  }
];
